In [2]:
#Installation des libraries(bibliothèques)
#Installer les dépendences (dependencies) nécessaires pour utiliser la bibliothèque (library) geoio
#Pour la library/bibliothèque geoio il faut installer la library/bibliothèque GDAL
#GDAL (Geospatial Data Abstraction Library) est une bibliothèque clé pour la gestion des données géospatiales,
#et c'est une dépendance courante pour de nombreux packages Python géospatiaux, y compris geoio.
#Utiliser dans l'anaconda prompt la commande suivante: conda install -c conda-forge gdal
# Cette commande dit à Conda d'installer le package GDAL à partir du la chaine conda-forge
#l'installation d'un package nécessite la compilation de code,
#ce qui signifie que vous avez besoin d'outils de développement installés sur votre système
#sur un système Linux vous installerez build-essential.
#Sous Windows, vous devrez peut-être installer Visual C++ Build Tools.
# Ensuite utiliser pip install gdal dans ton anaconda prompt
# Enfin dans la commande de l'anaconda prompt écrire: pip install geoio
# Si vous rencontrez une erreure de type ImportError: cannot import name 'Sequence' from 'collections'
#Vous devez Modifier le code source
# Vous devez ouvrier à l'aide éditeur comme notepad++ le fichier à cette localisation
# ~\anaconda3\Lib\site-packages\geoio\base.py
#Vous remplacez cette ligne de code "collections import Sequence"
#Par celle-ci from collections.abc import Sequence

In [3]:
# On charge les bibliothèques nécessaires
import pandas as pd
import numpy as np
import os
import geoio

In [4]:
#Chargement des données d'enquetes
df_base = pd.read_stata("C:/Users/d/Desktop/Programme du projet sur CNN pauvreté/Data/EHCVM_2018/dataout/ehcvm_welfare_CIV2018.dta")

df_gps = pd.read_stata("C:/Users/d/Desktop/Programme du projet sur CNN pauvreté/Data/EHCVM_2018/datain/Menage/s00_me_civ2018.dta")


In [5]:
print(df_base.shape,df_gps.shape)
print(df_base.head,df_gps.head)

(12992, 39) (12992, 52)
<bound method NDFrame.head of       country  year      hhid  grappe  menage  vague      zae  \
0         CIV  2018     101.0       1       1      1  ABIDJAN   
1         CIV  2018     102.0       1       2      1  ABIDJAN   
2         CIV  2018     103.0       1       3      1  ABIDJAN   
3         CIV  2018     104.0       1       4      1  ABIDJAN   
4         CIV  2018     105.0       1       5      1  ABIDJAN   
...       ...   ...       ...     ...     ...    ...      ...   
12987     CIV  2019  108408.0    1084       8      2   CENTRE   
12988     CIV  2019  108409.0    1084       9      2   CENTRE   
12989     CIV  2019  108410.0    1084      10      2   CENTRE   
12990     CIV  2019  108411.0    1084      11      2   CENTRE   
12991     CIV  2019  108412.0    1084      12      2   CENTRE   

                   region  milieu         milieu2  ...          dali  \
0      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...  2.580680e+06   
1      AUTONOME D'ABI

In [6]:
df_base.info()
df_gps.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12992 entries, 0 to 12991
Data columns (total 39 columns):
 #   Column     Non-Null Count  Dtype   
---  ------     --------------  -----   
 0   country    12992 non-null  object  
 1   year       12992 non-null  int16   
 2   hhid       12992 non-null  float32 
 3   grappe     12992 non-null  int16   
 4   menage     12992 non-null  int8    
 5   vague      12992 non-null  int8    
 6   zae        12992 non-null  category
 7   region     12992 non-null  category
 8   milieu     12992 non-null  category
 9   milieu2    12992 non-null  category
 10  hhweight   12992 non-null  float32 
 11  hhsize     12992 non-null  int8    
 12  eqadu1     12992 non-null  float64 
 13  eqadu2     12992 non-null  float32 
 14  hgender    12992 non-null  category
 15  hage       12992 non-null  int16   
 16  hmstat     12992 non-null  category
 17  hreligion  12992 non-null  category
 18  hnation    12992 non-null  category
 19  hethnie    10725 non-null

In [7]:
# Imprimer les noms de toutes les colonnes de la dataframe df_base
print("Les noms des colonnes dans la data frame sont:")
for column in df_base:
    print(column)

Les noms des colonnes dans la data frame sont:
country
year
hhid
grappe
menage
vague
zae
region
milieu
milieu2
hhweight
hhsize
eqadu1
eqadu2
hgender
hage
hmstat
hreligion
hnation
hethnie
halfab
heduc
hdiploma
hhandig
hactiv7j
hactiv12m
hbranch
hsectins
hcsp
dali
dnal
dtot
dtet
pcexp
zref
def_spa
def_temp
decile
quintile


In [8]:
# Imprimer les noms de toutes les colonnes de la dataframe df_gps
print("Les noms des colonnes dans la data frame sont:")
for column in df_gps:
    print(column)    

Les noms des colonnes dans la data frame sont:
interview__key
interview__id
grappe
menage
vague
GPS__Latitude
GPS__Longitude
GPS__Accuracy
GPS__Altitude
GPS__Timestamp
nom_prenom_cm
localisation_menage
s00q00
s00q01
s00q02
s00q03
s00q04
s00q05
s00q05_autre
s00q06
s00q07
s00q08
s00q09
s00q10
s00q11
s00q12
s00q13a
s00q13
s00q14
s00q15a
s00q15
s00q16
s00q17a
s00q17
s00q18
s00q19
s00q20
s00q21
s00q22
visite1
s00q23a
visite2
s00q24a
visite3
s00q25a
s00q23b
s00q24b
s00q25b
s00q28
s00q27
format_interview
observation


In [9]:
#J'ajoute les coordonnées GPS et je fusionne par les colonnes 
merged_df=pd.merge(df_base,df_gps,on=["grappe","menage","vague"], how='inner')


In [10]:
# Les informations sur les données fusionées
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12992 entries, 0 to 12991
Data columns (total 88 columns):
 #   Column               Non-Null Count  Dtype   
---  ------               --------------  -----   
 0   country              12992 non-null  object  
 1   year                 12992 non-null  int16   
 2   hhid                 12992 non-null  float32 
 3   grappe               12992 non-null  int16   
 4   menage               12992 non-null  int8    
 5   vague                12992 non-null  int8    
 6   zae                  12992 non-null  category
 7   region               12992 non-null  category
 8   milieu               12992 non-null  category
 9   milieu2              12992 non-null  category
 10  hhweight             12992 non-null  float32 
 11  hhsize               12992 non-null  int8    
 12  eqadu1               12992 non-null  float64 
 13  eqadu2               12992 non-null  float32 
 14  hgender              12992 non-null  category
 15  hage               

In [11]:
print(merged_df.isna())

       country   year   hhid  grappe  menage  vague    zae  region  milieu  \
0        False  False  False   False   False  False  False   False   False   
1        False  False  False   False   False  False  False   False   False   
2        False  False  False   False   False  False  False   False   False   
3        False  False  False   False   False  False  False   False   False   
4        False  False  False   False   False  False  False   False   False   
...        ...    ...    ...     ...     ...    ...    ...     ...     ...   
12987    False  False  False   False   False  False  False   False   False   
12988    False  False  False   False   False  False  False   False   False   
12989    False  False  False   False   False  False  False   False   False   
12990    False  False  False   False   False  False  False   False   False   
12991    False  False  False   False   False  False  False   False   False   

       milieu2  ...  s00q24a  visite3  s00q25a  s00q23b  s00q24

In [12]:
# les valeurs NaN (pas un nombre) dans la Dataframe
nan_valeurs = df_gps.isna()

# Compte le nombre de valuers NaN dans chaque colonne
nan_compte = nan_valeurs.sum()

# Imprime le décompte des valeurs NaN pour chaque colonne
print(nan_compte)

# Rapport détaillé avec les colonnes qui ont au moins une valeur NaN
colonnes_avc_nan = nan_compte[nan_compte > 0]
print("Colonnes avec au moins une valeur NaN:")
print(colonnes_avc_nan)


interview__key             0
interview__id              0
grappe                     0
menage                     0
vague                      0
GPS__Latitude             12
GPS__Longitude            12
GPS__Accuracy             12
GPS__Altitude             12
GPS__Timestamp             0
nom_prenom_cm              0
localisation_menage        0
s00q00                     0
s00q01                     0
s00q02                     0
s00q03                     0
s00q04                     0
s00q05                     0
s00q05_autre               0
s00q06                     0
s00q07                     0
s00q08                     0
s00q09                 12992
s00q10                     0
s00q11                     0
s00q12                     0
s00q13a                    3
s00q13                     0
s00q14                     0
s00q15a                    2
s00q15                     0
s00q16                     0
s00q17a                 9550
s00q17                     0
s00q18        

In [13]:
df_gps.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12992 entries, 0 to 12991
Data columns (total 52 columns):
 #   Column               Non-Null Count  Dtype   
---  ------               --------------  -----   
 0   interview__key       12992 non-null  object  
 1   interview__id        12992 non-null  object  
 2   grappe               12992 non-null  int16   
 3   menage               12992 non-null  int32   
 4   vague                12992 non-null  int8    
 5   GPS__Latitude        12980 non-null  float64 
 6   GPS__Longitude       12980 non-null  float64 
 7   GPS__Accuracy        12980 non-null  float64 
 8   GPS__Altitude        12980 non-null  float64 
 9   GPS__Timestamp       12992 non-null  object  
 10  nom_prenom_cm        12992 non-null  object  
 11  localisation_menage  12992 non-null  object  
 12  s00q00               12992 non-null  category
 13  s00q01               12992 non-null  category
 14  s00q02               12992 non-null  category
 15  s00q03             

In [14]:
#Une fonction qui permet d'enlever certaines colonnes

def enlever_colonnes(dataframe):
    
    return dataframe.iloc[:,:48]

#Créer une base de donnée qui est la version reduite de notre dataframe fusionnée
df_reduit=enlever_colonnes(merged_df)

In [15]:
df_reduit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12992 entries, 0 to 12991
Data columns (total 48 columns):
 #   Column               Non-Null Count  Dtype   
---  ------               --------------  -----   
 0   country              12992 non-null  object  
 1   year                 12992 non-null  int16   
 2   hhid                 12992 non-null  float32 
 3   grappe               12992 non-null  int16   
 4   menage               12992 non-null  int8    
 5   vague                12992 non-null  int8    
 6   zae                  12992 non-null  category
 7   region               12992 non-null  category
 8   milieu               12992 non-null  category
 9   milieu2              12992 non-null  category
 10  hhweight             12992 non-null  float32 
 11  hhsize               12992 non-null  int8    
 12  eqadu1               12992 non-null  float64 
 13  eqadu2               12992 non-null  float32 
 14  hgender              12992 non-null  category
 15  hage               

In [16]:
df_reduit.isna()

country   year   hhid  grappe  menage  vague    zae  region  milieu  \
0        False  False  False   False   False  False  False   False   False   
1        False  False  False   False   False  False  False   False   False   
2        False  False  False   False   False  False  False   False   False   
3        False  False  False   False   False  False  False   False   False   
4        False  False  False   False   False  False  False   False   False   
...        ...    ...    ...     ...     ...    ...    ...     ...     ...   
12987    False  False  False   False   False  False  False   False   False   
12988    False  False  False   False   False  False  False   False   False   
12989    False  False  False   False   False  False  False   False   False   
12990    False  False  False   False   False  False  False   False   False   
12991    False  False  False   False   False  False  False   False   False   

       milieu2  ...  quintile  interview__key  interview__id  GPS__Latitude  \
0        False  ...     False           False          False          False   
1        False  ...     False           False          False          False   
2        False  ...     False           False          False          False   
3        False  ...     False           False          False          False   
4        False  ...     False           False          False          False   
...        ...  ...       ...             ...            ...            ...   
12987    False  ...     False           False          False          False   
12988    False  ...     False           False          False          False   
12989    False  ...     False           False          False          False   
12990    False  ...     False           False          False          False   
12991    False  ...     False           False          False          False   

       GPS__Longitude  GPS__Accuracy  GPS__Altitude  GPS__Timestamp  \
0               False          False          False           False   
1               False          False          False           False   
2               False          False          False           False   
3               False          False          False           False   
4               False          False          False           False   
...               ...            ...            ...             ...   
12987           False          False          False           False   
12988           False          False          False           False   
12989           False          False          False           False   
12990           False          False          False           False   
12991           False          False          False           False   

       nom_prenom_cm  localisation_menage  
0              False                False  
1              False                False  
2              False                False  
3              False                False  
4              False                False  
...              ...                  ...  
12987          False                False  
12988          False                False  
12989          False                False  
12990          False                False  
12991          False                False  

[12992 rows x 48 columns]

In [17]:
# Option B: Enlever les valeurs manquantes
#df_reduit.dropna(inplace=True)
df_reduit_cleaned = df_reduit.dropna(subset=['GPS__Latitude', 'GPS__Longitude', 'GPS__Accuracy', 'GPS__Altitude'])
df_reduit_cleaned.to_csv('C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/Data/CIV/df_reduit_cleaned2.csv', index=False)

In [18]:
df_reduit_cleaned.shape

(12980, 48)

In [19]:
# les valeurs NaN (pas un nombre) dans la Dataframe
nan_valeurs = df_reduit_cleaned.isna()

# Count the number of NaN values in each column
nan_compte = nan_valeurs.sum()

# Print the count of NaN values for each column
print(nan_compte)

# If you want to get a more detailed report, you could print columns with at least one NaN value
colonnes_avc_nan = nan_compte[nan_compte > 0]
print("Colonnes avec au moins une valeur NaN:")
print(colonnes_avc_nan)

country                   0
year                      0
hhid                      0
grappe                    0
menage                    0
vague                     0
zae                       0
region                    0
milieu                    0
milieu2                   0
hhweight                  0
hhsize                    0
eqadu1                    0
eqadu2                    0
hgender                   0
hage                      0
hmstat                    0
hreligion                 0
hnation                   0
hethnie                2265
halfab                    0
heduc                     0
hdiploma                  0
hhandig                   0
hactiv7j                  0
hactiv12m                 0
hbranch                1000
hsectins               1000
hcsp                   1000
dali                      0
dnal                      0
dtot                      0
dtet                      0
pcexp                     0
zref                      0
def_spa             

In [20]:
df_reduit_cleaned.to_csv('C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/Data/CIV/df_EHVCM2018_upd2.csv', index=False)

In [21]:
!pip install folium

In [22]:
import pandas as pd
import folium

#fichier_sortie est le nom du fichier où sauvegarder la carte
def creer_carte_gps(dataframe, fichier_sortie):
    # Calcul des moyennes des latitudes et longitudes pour centrer la carte
    moyenne_latitude = dataframe['GPS__Latitude'].mean()
    moyenne_longitude = dataframe['GPS__Longitude'].mean()
    
    # Création de la carte avec folium
    carte = folium.Map(location=[moyenne_latitude, moyenne_longitude], zoom_start=7)
    
    # Ajout des points GPS à la carte
    for _, row in dataframe.iterrows():
        folium.Marker([row['GPS__Latitude'], row['GPS__Longitude']]).add_to(carte)
    
    # Sauvegarde de la carte dans un fichier HTML
    carte.save(fichier_sortie)
    print(f"Carte sauvegardée sous : {fichier_sortie}")


In [23]:
# Utilisation de la fonction
fichier_sortie = r'C:\Users\d\Desktop\Programme du projet sur CNN pauvreté2\Data\carte_gps.html'  # Nom du fichier où sauvegarder la carte
creer_carte_gps(df_reduit_cleaned, fichier_sortie)

Carte sauvegardée sous : C:\Users\d\Desktop\Programme du projet sur CNN pauvreté2\Data\carte_gps.html


In [24]:
#Definition de directoire
os.getcwd() 
NIGHTLIGHTS_DIRS = 'C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/Data/NIGHTLIGHTS'
BASE_DIR = 'C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/'
NIGHTLIGHTS_DIRS = 'C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/Data/NIGHTLIGHTS'
NIGHTLIGHTS_FILES = "C:\\Users\\d\\Desktop\\Programme du projet sur CNN pauvreté2\\Data\\NIGHTLIGHTS\\VNL_v2_npp_2018_global_vcmslcfg_c202101211500.cvg.tif"
COUNTRIES_DIR = os.path.join(BASE_DIR, 'Data','CIV') 


In [25]:
#Affichage des chemins aux différents dossiers
print(NIGHTLIGHTS_FILES,NIGHTLIGHTS_DIRS)

C:\Users\d\Desktop\Programme du projet sur CNN pauvreté2\Data\NIGHTLIGHTS\VNL_v2_npp_2018_global_vcmslcfg_c202101211500.cvg.tif C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/Data/NIGHTLIGHTS


In [26]:
#Affichage des chemins aux différents dossiers
print(COUNTRIES_DIR)

C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/Data\CIV


In [27]:
import sys
sys.path.append(BASE_DIR)

create_space est conçue pour créer une surface carrée centrée autour d'un point géographique donné, défini par ses coordonnées de latitude et de longitude. L'objectif principal de cette fonction est de calculer les coordonnées des quatre coins d'un carré autour d'un point central, de manière à ce que chaque côté du carré mesure s kilomètres de long

In [28]:
import math
import pandas as pd
def create_space(lat, lon, s):
    """Crée une surface de s mètres par s mètres de surface carré centré sur les coordonnées (latitute,longitude)"""
    lat=float(lat)
    lon=float(lon)
    v1 = (180/math.pi)*(s/6378137)
    v2=  (180/math.pi)*(s/6378137)/math.cos(lat)
    return lat - v1, lon - v2, lat + v1, lon + v2

In [29]:
!pip install folium
import folium

In [100]:
def visualize_on_map(lat,lon, min_lat, min_lon, max_lat, max_lon):
    
    
    # Crée un Map
    m = folium.Map(location=[lat,lon], zoom_start=16)

    # Mettre des marqueurs au centre
    folium.Marker([lat,lon], popup='Center', icon=folium.Icon(color='red')).add_to(m)

    # Mettre des marqueurs pour les coins
    folium.Marker([min_lat, min_lon], popup='Min Lat, Min Lon', icon=folium.Icon(color='green')).add_to(m)
    folium.Marker([max_lat, max_lon], popup='Max Lat, Max Lon', icon=folium.Icon(color='blue')).add_to(m)
    
    # Dessine le rectangle
    bounds = [(min_lat, min_lon), (max_lat, max_lon)]
    folium.Rectangle(bounds=bounds, color='#ff7800', fill=True, fill_opacity=0.2).add_to(m)

    # Montre le Map
    return m

In [101]:
# Exemple d'utilisation
lat, lon = 5.3689, 3.9417 # Abidjan, par exemple
min_lat, min_lon, max_lat, max_lon = create_space(5.3689,-3.9417, s=100) #s=100 c'est 100 mètres
visualize_on_map(lat,lon, min_lat, min_lon, max_lat, max_lon)


In [31]:
tif=geoio.GeoImage(os.path.join(NIGHTLIGHTS_DIRS, 'VNL_v2_npp_2018_global_vcmslcfg_c202101211500.cvg.tif'))

In [32]:
tif

Class Name        : GeoImage
Driver Name       : GTiff
Data Type         : UInt16
File Name         : C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/Dat
                    a/NIGHTLIGHTS\VNL_v2_npp_2018_global_vcmslcfg_c202101211500.
                    cvg.tif
File List         : ['C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/D
                    ata/NIGHTLIGHTS\\VNL_v2_npp_2018_global_vcmslcfg_c2021012115
                    00.cvg.tif']
Dimensions        : (1, 86401, 33601) (nlayers, nrows, ncols)
Resolution        : (0.0041666667, 0.0041666667) (x,y)
Extent            : (-180.00208333335, 75.00208333335, 180.00208621335,
                    -65.00208445335001) (ul_x, ul_y, lr_x, lr_y)
Projection String : GEOGCS["WGS 84",
                     DATUM["WGS_1984",
                         SPHEROID["WGS 84",6378137,298.257223563,
                             AUTHORITY["EPSG","7030"]],
                         AUTHORITY["EPSG","6326"]],
                     PRIMEM["

In [33]:
print(tif.shape)
print(type(tif))

(1, 86401, 33601)
<class 'geoio.base.GeoImage'>


In [34]:
tif.meta

file_name          : C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/Da
                     ta/NIGHTLIGHTS\VNL_v2_npp_2018_global_vcmslcfg_c20210121150
                     0.cvg.tif
file_list          : ['C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/
                     Data/NIGHTLIGHTS\\VNL_v2_npp_2018_global_vcmslcfg_c20210121
                     1500.cvg.tif']
driver_name        : GTiff
no_data_value      : None
gdal_dtype         : 2
gdal_dtype_name    : UInt16
pixels             : 2903160001
shape              : (1, 86401, 33601)
geo_transform      : (-180.00208333335, 0.0041666667, 0.0, 75.00208333335, 0.0,
                     -0.0041666667)
resolution         : (0.0041666667, 0.0041666667)
extent             : (-180.00208333335, 75.00208333335, 180.00208621335,
                     -65.00208445335001)
projection_string  : GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,
                     298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["E

- La méthode get_data() est utilisée pour extraire les données d'image sous-jacentes de l'objet img et les retourner sous forme d'un tableau NumPy. Ce tableau représente les valeurs de pixels de l'image, organisées dans un format qui reflète la disposition spatiale de ces pixels (par exemple, en termes de hauteur et de largeur de l'image, et potentiellement aussi en termes de canaux de couleur ou d'autres dimensions pour des images multispectrales ou temporelles).

In [35]:
tif_array = np.squeeze(tif.get_data())

In [36]:
tif_array

array([[359, 358, 357, ..., 359, 359, 198],
       [359, 356, 356, ..., 359, 359, 198],
       [359, 356, 350, ..., 359, 359, 198],
       ...,
       [356, 356, 356, ..., 356, 356, 336],
       [356, 355, 356, ..., 356, 356, 336],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=uint16)

    Dimensions        : (1, 86401, 33601) (nlayers, nrows, ncols)  
- 1 couche
- 86401 lignes
- 33601 colonnes
(1, 86401, 33601)
- La première dimension a une taille de 1, ce qui signifie qu'il y a potentiellement une seule couche ou un seul canal de données. C'est une dimension superflue pour certains types d'analyses, d'où l'intérêt de l'utiliser avec np.squeeze() pour la supprimer si elle n'est pas nécessaire.
- La deuxième dimension a une taille de 86401, ce qui représente le nombre de pixels dans une direction de l'image (hauteur). (ligne)
- La troisième dimension a une taille de 33601, ce qui représente le nombre de pixels dans l'autre direction de l'image (largeur). (colonne)
- np.squeeze(tif.get_data()), la méthode np.squeeze() enlève la première dimension superflue (de taille 1), et vous obtenez un tableau tif_array avec les dimensions (86401, 33601) 


In [37]:
tif_array.shape[0]

33601

In [38]:
tif_array.shape[1]

86401

- On constate que tif_array.shape[0] est lié à la colonne tif_array.shape[1] est lié aux lignes

In [39]:
tif.proj_to_raster(5.3689, -3.9417)

(44489.03564409171, 18946.507848431935)

In [40]:
#Essai de la méthode proj_to_raster
a,b=tif.proj_to_raster(5.3689, -3.9417) #latitude et longitude
tif_array[int(b),int(a)] #On rend en nombre entier et on inverse l'ordre, on met longitude d'abord
                         #Si je ne renverse pas l'ordre, j'obtiens une erreur

182

In [41]:
tif_array[18966,44482]

182

In [42]:
# Fonction pour convertir lat, lon en valeur nightlight
def get_nightlight_value(lat, lon):
    a, b = tif.proj_to_raster(lat, lon)  # Convertit lat, lon en indices raster
    return tif_array[int(b), int(a)]     # Retourne la valeur correspondante dans tif_array

# La fonction s'applique à chaque ligne du DataFrame et créer la nouvelle colonne
df_reduit_cleaned['nightlight_0'] = df_reduit_cleaned.apply(lambda row: get_nightlight_value(row['GPS__Latitude'], row['GPS__Longitude']), axis=1)


C:\Users\d\AppData\Local\Temp\ipykernel_24360\541679126.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_reduit_cleaned['nightlight_0'] = df_reduit_cleaned.apply(lambda row: get_nightlight_value(row['GPS__Latitude'], row['GPS__Longitude']), axis=1)


In [43]:
df_reduit_cleaned

country  year      hhid  grappe  menage  vague      zae  \
0         CIV  2018     101.0       1       1      1  ABIDJAN   
1         CIV  2018     102.0       1       2      1  ABIDJAN   
2         CIV  2018     103.0       1       3      1  ABIDJAN   
3         CIV  2018     104.0       1       4      1  ABIDJAN   
4         CIV  2018     105.0       1       5      1  ABIDJAN   
...       ...   ...       ...     ...     ...    ...      ...   
12987     CIV  2019  108408.0    1084       8      2   CENTRE   
12988     CIV  2019  108409.0    1084       9      2   CENTRE   
12989     CIV  2019  108410.0    1084      10      2   CENTRE   
12990     CIV  2019  108411.0    1084      11      2   CENTRE   
12991     CIV  2019  108412.0    1084      12      2   CENTRE   

                   region  milieu         milieu2  ...  interview__key  \
0      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...     37-12-91-96   
1      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...     66-72-76-42   
2      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...     00-21-02-40   
3      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...     69-94-30-00   
4      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...     92-17-10-43   
...                   ...     ...             ...  ...             ...   
12987             MORONOU   Rural           Rural  ...     50-03-51-41   
12988             MORONOU   Rural           Rural  ...     82-42-90-66   
12989             MORONOU   Rural           Rural  ...     21-28-94-39   
12990             MORONOU   Rural           Rural  ...     24-86-66-78   
12991             MORONOU   Rural           Rural  ...     11-53-13-51   

                          interview__id  GPS__Latitude  GPS__Longitude  \
0      2eb3d29ba9814aa9bf99d6908559e7d2       5.340541       -4.026030   
1      99990d719d6243a38fad96a4d7477742       5.340402       -4.025834   
2      6cf633ef989c4a6a93ec483de1fd8193       5.340151       -4.025953   
3      67feab4e35d141679ec4b867a59cba19       5.340500       -4.026202   
4      dc1f1fa87d8e433e8891a4e55a8baca0       5.339820       -4.025066   
...                                 ...            ...             ...   
12987  103cff29baaf4405863e1043897aa6dc       6.546733       -4.508211   
12988  e3a3deb8965e45c18018d1e5d103d914       6.549112       -4.505840   
12989  45397589c6d44a478051e4089a884c97       6.551556       -4.507530   
12990  505343592b0f4b8b8ede9980f714b8ab       6.552345       -4.507551   
12991  d3431cc126bd44b38fa4976fc3adb753       6.550105       -4.508566   

      GPS__Accuracy  GPS__Altitude       GPS__Timestamp nom_prenom_cm  \
0              46.0           39.0  2018-10-29T17:56:23                 
1              47.0           28.0  2018-10-29T17:54:35                 
2              35.0           68.0  2018-10-29T17:51:50                 
3              32.0           59.0  2018-10-29T19:48:39                 
4              49.0           72.0  2018-10-29T18:45:09                 
...             ...            ...                  ...           ...   
12987           7.0          134.0  2019-06-16T19:42:05                 
12988          36.0          131.0  2019-06-17T08:10:57                 
12989          29.0          118.0  2019-06-16T09:30:14                 
12990          19.0          157.0  2019-06-16T10:18:13                 
12991           6.0          134.0  2019-06-16T08:39:10                 

      localisation_menage nightlight_0  
0                                  182  
1                                  182  
2                                  182  
3                                  182  
4                                  182  
...                   ...          ...  
12987                              175  
12988                              175  
12989                              175  
12990                              176  
12991                              175  

[12980 rows x 49 columns]

In [44]:
# Compter le nombre de valeurs NaN dans 'nightlights_0'
nan_count = df_reduit_cleaned['nightlight_0'].isna().sum()
print(f"Nombre de valeurs NaN dans 'nightlights_0': {nan_count}")

Nombre de valeurs NaN dans 'nightlights_0': 0


##### Nightlight_0
- Nightlight_0 represente la valeur exact de l'intensité lumineuse nocturne aux différents points GPS

In [45]:
import matplotlib
matplotlib.use('TkAgg')  # Switch to a GUI backend
import matplotlib.pyplot as plt

# Your plotting code here
plt.hist(df_reduit_cleaned['nightlight_0'], bins=50, color='blue', edgecolor='black')
plt.title('Histogramme de Nightlight_0')
plt.xlabel('Intensité Lumineuse nocturnes')
plt.ylabel('Fréquence')
plt.show()
plt.savefig('C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/graphs/histogramme_nightlight_0.png')

In [46]:
import matplotlib
matplotlib.use('TkAgg')  # Utilisation d'un backend GUI
import matplotlib.pyplot as plt

# Histogramme
plt.hist(df_reduit_cleaned['nightlight_0'], bins=50, color='blue', edgecolor='black')
plt.title('Histogramme de Nightlight_0')
plt.xlabel('Intensité Lumineuse nocturnes')
plt.ylabel('Fréquence')

# Sauvegarde
plt.savefig('C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/graphs/histogramme_nightlight_0.png')

# Affichage de l'histogramme
plt.show()

In [47]:
summary_stats = df_reduit_cleaned['nightlight_0'].describe()
print(summary_stats)

count    12980.000000
mean       180.877427
std          2.478476
min        169.000000
25%        181.000000
50%        182.000000
75%        182.000000
max        184.000000
Name: nightlight_0, dtype: float64


In [48]:
# Calcul de la corrélation entre 'pcexp' et 'nightlight_0'
#la corrélation de Pearson entre les colonnes pcexp et nightlight_0 et affiche le résultat.

correlation_pcexp_nightlight_0 = df_reduit_cleaned['pcexp'].corr(df_reduit_cleaned['nightlight_0'])

print(f"Corrélation entre 'pcexp' et 'nightlight_0': {correlation_pcexp_nightlight_0}")


Corrélation entre 'pcexp' et 'nightlight_0': 0.016663529173025635


- Une corrélation de 0.016663529173025635 entre les variables pcexp et nightlight_0 indique une relation linéaire très faible entre ces deux variables.

###### Scatterplot de nightlight_0

In [49]:
import matplotlib.pyplot as plt

# Créer le scatter plot
plt.figure(figsize=(10, 6))  # Définit la taille de la figure
plt.scatter(df_reduit_cleaned['pcexp'], df_reduit_cleaned['nightlight_0'], alpha=0.5)  # Crée le scatter plot
plt.title('Scatter plot entre pcexp et nightlight_0')  # Titre du graphique
plt.xlabel('pcexp')  # Label pour l'axe des x
plt.ylabel('nightlight_0')  # Label pour l'axe des y

# Sauvegarder le graphique dans le dossier 'graphs'
plt.savefig('C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/graphs/scatter_pcexp_vs_nightlight_0.png')

# Afficher le graphique
plt.show()


In [50]:
del tif_array
import gc
gc.collect() 
import psutil
psutil.virtual_memory()

svmem(total=16849256448, available=3178807296, percent=81.1, used=13670449152, free=3178807296)

### Les intensités lumineuses nocturnes considérant un rayon de 100 mètres

In [51]:
import math
import rasterio
from rasterio.mask import mask
from shapely.geometry import box
import numpy as np
import pandas as pd

path_to_tiff='C:\\Users\\d\\Desktop\\Programme du projet sur CNN pauvreté2\\Data\\NIGHTLIGHTS\\VNL_v2_npp_2018_global_vcmslcfg_c202101211500.cvg.tif'

def create_space_adjusted(lat, lon, s):
    """
    Calcul l'ajustement en degrés pour une distance `s` en mètres autour d'un point donné (lat, lon),
    prenant en compte la diminution de la distance couverte par un degré de longitude avec l'augmentation de la latitude.
    """
    # Rayon moyen de la Terre en mètres
    earth_radius = 6378137
    # Distance correspondant à un degré à l'équateur
    distance_per_degree = (2 * math.pi * earth_radius) / 360
    # Ajustement pour `s` mètres en degrés
    adjustment = s / distance_per_degree
    # Ajustement pour la longitude
    adjustment_lon = adjustment / math.cos(math.radians(lat))
    return box(lon - adjustment_lon, lat - adjustment, lon + adjustment_lon, lat + adjustment)

def calculate_nightlights_custom(df, path_to_tiff, distance_m=100):
    """
    Rempli un DataFrame avec l'intensité moyenne des lumières nocturnes pour des points définis par GPS__Latitude et GPS__Longitude,
    en utilisant une boîte de taille spécifiée autour de chaque point pour le calcul.
    """
    with rasterio.open(path_to_tiff) as src:
        nightlights = []
        for index, row in df.iterrows():
            # Créer une géométrie de boîte autour du point avec un ajustement pour `distance_m` mètres
            geom = create_space_adjusted(row['GPS__Latitude'], row['GPS__Longitude'], distance_m / 2)  # /2 pour obtenir la moitié de la distance de chaque côté
            
            # Utiliser mask pour découper l'image raster selon la géométrie calculée
            out_image, out_transform = mask(src, [geom], crop=True, all_touched=True)
            
            # Traitement des valeurs no_data du raster
            out_image = out_image.astype(float)
            out_image[out_image == src.nodata] = np.nan  # Convertir les no_data en NaN
            
            # Calcul de la moyenne, en excluant les NaN
            mean_val = np.nanmean(out_image)
            nightlights.append(mean_val)
        
        df['nightlights'] = nightlights

    return df


In [52]:
'''
def get_nightlight_pixel_values(df, path_to_tiff, distance_m=100):
    """
    Récupère les valeurs des pixels pour l'intensité lumineuse nocturne autour des points spécifiés dans un DataFrame.
    """
    with rasterio.open(path_to_tiff) as src:
        all_pixel_values = []
        for index, row in df.iterrows():
            geom = create_space_adjusted(row['GPS__Latitude'], row['GPS__Longitude'], distance_m / 2)
            out_image, out_transform = mask(src, [geom], crop=True, all_touched=True)
            
            # Convertir no_data en NaN et aplatir le tableau pour avoir une liste de valeurs
            out_image = out_image.astype(float)
            out_image[out_image == src.nodata] = np.nan  # Remplacer no_data par NaN
            pixel_values = out_image.flatten()
            pixel_values = pixel_values[~np.isnan(pixel_values)]  # Enlever les NaN
            
            all_pixel_values.append(pixel_values)
        
        return all_pixel_values
'''

'\ndef get_nightlight_pixel_values(df, path_to_tiff, distance_m=100):\n    """\n    Récupère les valeurs des pixels pour l\'intensité lumineuse nocturne autour des points spécifiés dans un DataFrame.\n    """\n    with rasterio.open(path_to_tiff) as src:\n        all_pixel_values = []\n        for index, row in df.iterrows():\n            geom = create_space_adjusted(row[\'GPS__Latitude\'], row[\'GPS__Longitude\'], distance_m / 2)\n            out_image, out_transform = mask(src, [geom], crop=True, all_touched=True)\n            \n            # Convertir no_data en NaN et aplatir le tableau pour avoir une liste de valeurs\n            out_image = out_image.astype(float)\n            out_image[out_image == src.nodata] = np.nan  # Remplacer no_data par NaN\n            pixel_values = out_image.flatten()\n            pixel_values = pixel_values[~np.isnan(pixel_values)]  # Enlever les NaN\n            \n            all_pixel_values.append(pixel_values)\n        \n        return all_pixel_v

In [53]:
!pip install geopandas matplotlib

In [54]:
import geopandas as gpd
import matplotlib.pyplot as plt
from shapely.geometry import Point, box
import math

def create_space_adjusted(lat, lon, s):
    earth_radius = 6378137
    distance_per_degree = (2 * math.pi * earth_radius) / 360
    adjustment = s / distance_per_degree
    adjustment_lon = adjustment / math.cos(math.radians(lat))
    return box(lon - adjustment_lon, lat - adjustment, lon + adjustment_lon, lat + adjustment)

def visualize_box_and_save(lat, lon, distance_m=100, save_path='C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/graphs/box_visualization_100m.png'):
    geom = create_space_adjusted(lat, lon, distance_m / 2)
    
    gdf_box = gpd.GeoDataFrame({'id': [1], 'geometry': [geom]})
    gdf_point = gpd.GeoDataFrame({'id': [1], 'geometry': [Point(lon, lat)]})
    
    fig, ax = plt.subplots()
    gdf_box.boundary.plot(ax=ax, color='red', label='100m Box')
    gdf_point.plot(ax=ax, color='blue', marker='o', label='Point')
    
    plt.legend()
    plt.xlabel('Longitude')
    plt.ylabel('Latitude')
    plt.title('Visualisation de boite de 100m autour dun Point')

    # Sauvegarder l'image
    plt.savefig(save_path, bbox_inches='tight')
    plt.close()

In [55]:
# Utiliser la fonction avec un chemin de sauvegarde spécifique
visualize_box_and_save(lat=48.8566, lon=2.3522, save_path='C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/graphs/box_visualization_100m.png')

In [56]:
calculate_nightlights_custom(df_reduit_cleaned, path_to_tiff, distance_m=100)

C:\Users\d\AppData\Local\Temp\ipykernel_24360\4019309744.py:47: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['nightlights'] = nightlights


country  year      hhid  grappe  menage  vague      zae  \
0         CIV  2018     101.0       1       1      1  ABIDJAN   
1         CIV  2018     102.0       1       2      1  ABIDJAN   
2         CIV  2018     103.0       1       3      1  ABIDJAN   
3         CIV  2018     104.0       1       4      1  ABIDJAN   
4         CIV  2018     105.0       1       5      1  ABIDJAN   
...       ...   ...       ...     ...     ...    ...      ...   
12987     CIV  2019  108408.0    1084       8      2   CENTRE   
12988     CIV  2019  108409.0    1084       9      2   CENTRE   
12989     CIV  2019  108410.0    1084      10      2   CENTRE   
12990     CIV  2019  108411.0    1084      11      2   CENTRE   
12991     CIV  2019  108412.0    1084      12      2   CENTRE   

                   region  milieu         milieu2  ...  \
0      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...   
1      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...   
2      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...   
3      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...   
4      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...   
...                   ...     ...             ...  ...   
12987             MORONOU   Rural           Rural  ...   
12988             MORONOU   Rural           Rural  ...   
12989             MORONOU   Rural           Rural  ...   
12990             MORONOU   Rural           Rural  ...   
12991             MORONOU   Rural           Rural  ...   

                          interview__id  GPS__Latitude  GPS__Longitude  \
0      2eb3d29ba9814aa9bf99d6908559e7d2       5.340541       -4.026030   
1      99990d719d6243a38fad96a4d7477742       5.340402       -4.025834   
2      6cf633ef989c4a6a93ec483de1fd8193       5.340151       -4.025953   
3      67feab4e35d141679ec4b867a59cba19       5.340500       -4.026202   
4      dc1f1fa87d8e433e8891a4e55a8baca0       5.339820       -4.025066   
...                                 ...            ...             ...   
12987  103cff29baaf4405863e1043897aa6dc       6.546733       -4.508211   
12988  e3a3deb8965e45c18018d1e5d103d914       6.549112       -4.505840   
12989  45397589c6d44a478051e4089a884c97       6.551556       -4.507530   
12990  505343592b0f4b8b8ede9980f714b8ab       6.552345       -4.507551   
12991  d3431cc126bd44b38fa4976fc3adb753       6.550105       -4.508566   

       GPS__Accuracy GPS__Altitude       GPS__Timestamp nom_prenom_cm  \
0               46.0          39.0  2018-10-29T17:56:23                 
1               47.0          28.0  2018-10-29T17:54:35                 
2               35.0          68.0  2018-10-29T17:51:50                 
3               32.0          59.0  2018-10-29T19:48:39                 
4               49.0          72.0  2018-10-29T18:45:09                 
...              ...           ...                  ...           ...   
12987            7.0         134.0  2019-06-16T19:42:05                 
12988           36.0         131.0  2019-06-17T08:10:57                 
12989           29.0         118.0  2019-06-16T09:30:14                 
12990           19.0         157.0  2019-06-16T10:18:13                 
12991            6.0         134.0  2019-06-16T08:39:10                 

      localisation_menage nightlight_0 nightlights  
0                                  182       175.0  
1                                  182       175.0  
2                                  182       175.0  
3                                  182       175.0  
4                                  182       175.0  
...                   ...          ...         ...  
12987                              175       185.0  
12988                              175       185.0  
12989                              175       185.0  
12990                              176       185.0  
12991                              175       185.0  

[12980 rows x 50 columns]

In [57]:
df_reduit_cleaned

country  year      hhid  grappe  menage  vague      zae  \
0         CIV  2018     101.0       1       1      1  ABIDJAN   
1         CIV  2018     102.0       1       2      1  ABIDJAN   
2         CIV  2018     103.0       1       3      1  ABIDJAN   
3         CIV  2018     104.0       1       4      1  ABIDJAN   
4         CIV  2018     105.0       1       5      1  ABIDJAN   
...       ...   ...       ...     ...     ...    ...      ...   
12987     CIV  2019  108408.0    1084       8      2   CENTRE   
12988     CIV  2019  108409.0    1084       9      2   CENTRE   
12989     CIV  2019  108410.0    1084      10      2   CENTRE   
12990     CIV  2019  108411.0    1084      11      2   CENTRE   
12991     CIV  2019  108412.0    1084      12      2   CENTRE   

                   region  milieu         milieu2  ...  \
0      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...   
1      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...   
2      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...   
3      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...   
4      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...   
...                   ...     ...             ...  ...   
12987             MORONOU   Rural           Rural  ...   
12988             MORONOU   Rural           Rural  ...   
12989             MORONOU   Rural           Rural  ...   
12990             MORONOU   Rural           Rural  ...   
12991             MORONOU   Rural           Rural  ...   

                          interview__id  GPS__Latitude  GPS__Longitude  \
0      2eb3d29ba9814aa9bf99d6908559e7d2       5.340541       -4.026030   
1      99990d719d6243a38fad96a4d7477742       5.340402       -4.025834   
2      6cf633ef989c4a6a93ec483de1fd8193       5.340151       -4.025953   
3      67feab4e35d141679ec4b867a59cba19       5.340500       -4.026202   
4      dc1f1fa87d8e433e8891a4e55a8baca0       5.339820       -4.025066   
...                                 ...            ...             ...   
12987  103cff29baaf4405863e1043897aa6dc       6.546733       -4.508211   
12988  e3a3deb8965e45c18018d1e5d103d914       6.549112       -4.505840   
12989  45397589c6d44a478051e4089a884c97       6.551556       -4.507530   
12990  505343592b0f4b8b8ede9980f714b8ab       6.552345       -4.507551   
12991  d3431cc126bd44b38fa4976fc3adb753       6.550105       -4.508566   

       GPS__Accuracy GPS__Altitude       GPS__Timestamp nom_prenom_cm  \
0               46.0          39.0  2018-10-29T17:56:23                 
1               47.0          28.0  2018-10-29T17:54:35                 
2               35.0          68.0  2018-10-29T17:51:50                 
3               32.0          59.0  2018-10-29T19:48:39                 
4               49.0          72.0  2018-10-29T18:45:09                 
...              ...           ...                  ...           ...   
12987            7.0         134.0  2019-06-16T19:42:05                 
12988           36.0         131.0  2019-06-17T08:10:57                 
12989           29.0         118.0  2019-06-16T09:30:14                 
12990           19.0         157.0  2019-06-16T10:18:13                 
12991            6.0         134.0  2019-06-16T08:39:10                 

      localisation_menage nightlight_0 nightlights  
0                                  182       175.0  
1                                  182       175.0  
2                                  182       175.0  
3                                  182       175.0  
4                                  182       175.0  
...                   ...          ...         ...  
12987                              175       185.0  
12988                              175       185.0  
12989                              175       185.0  
12990                              176       185.0  
12991                              175       185.0  

[12980 rows x 50 columns]

In [58]:
df_reduit_cleaned['nightlights'].isna

<bound method Series.isna of 0        175.0
1        175.0
2        175.0
3        175.0
4        175.0
         ...  
12987    185.0
12988    185.0
12989    185.0
12990    185.0
12991    185.0
Name: nightlights, Length: 12980, dtype: float64>

In [59]:
"""
import rasterio

# Chemin vers le fichier TIFF
path_to_tiff = 'C:\\Users\\d\\Desktop\\Programme du projet sur CNN pauvreté\\Data\\NIGHTLIGHTS\\VNL_v2_npp_2018_global_vcmslcfg_c202101211500.cvg.tif'

# Ouvrir le fichier TIFF avec rasterio
with rasterio.open(path_to_tiff) as src:
    # Transformer les coordonnées géographiques en coordonnées de pixels
    
    x, y = src.index(-4.026030, 5.340541)

    print(f"Coordonnées de pixel: x={x}, y={y}")
"""

'\nimport rasterio\n\n# Chemin vers le fichier TIFF\npath_to_tiff = \'C:\\Users\\d\\Desktop\\Programme du projet sur CNN pauvreté\\Data\\NIGHTLIGHTS\\VNL_v2_npp_2018_global_vcmslcfg_c202101211500.cvg.tif\'\n\n# Ouvrir le fichier TIFF avec rasterio\nwith rasterio.open(path_to_tiff) as src:\n    # Transformer les coordonnées géographiques en coordonnées de pixels\n    \n    x, y = src.index(-4.026030, 5.340541)\n\n    print(f"Coordonnées de pixel: x={x}, y={y}")\n'

In [60]:
df_reduit_cleaned['nightlights']

0        175.0
1        175.0
2        175.0
3        175.0
4        175.0
         ...  
12987    185.0
12988    185.0
12989    185.0
12990    185.0
12991    185.0
Name: nightlights, Length: 12980, dtype: float64

In [61]:
import matplotlib.pyplot as plt

# Créer un histogramme de la colonne 'nightlights'
plt.hist(df_reduit_cleaned['nightlights'].dropna(), bins=20, edgecolor='black')
plt.title('Histogramme des Lumières Nocturnes')
plt.xlabel('Intensité Lumineuse Nocturne')
plt.ylabel('Fréquence')
plt.show()
plt.savefig('C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/graphs/histogramme_nightlights.png')


In [62]:
# Compter le nombre de valeurs NaN dans 'nightlights'
nan_count = df_reduit_cleaned['nightlights'].isna().sum()

print(f"Nombre de valeurs NaN dans 'nightlights': {nan_count}")


Nombre de valeurs NaN dans 'nightlights': 0


In [63]:
"""
import rasterio
from rasterio.mask import mask
from shapely.geometry import box
import numpy as np
import pandas as pd


import math
import rasterio
from rasterio.mask import mask
from shapely.geometry import box
import numpy as np
import pandas as pd

def calculate_nightlights_100m(df, path_to_tiff):
    with rasterio.open(path_to_tiff) as src:
        nightlights2 = []
        for index, row in df.iterrows():
            # Calcul de l'ajustement en degrés pour 100 mètres
            # Rayon moyen de la Terre en mètres
            earth_radius = 6371000
            # Distance correspondant à un degré à l'équateur
            distance_per_degree = (2 * math.pi * earth_radius) / 360
            # Ajustement pour 100 mètres en degrés
            adjustment = 100 / distance_per_degree
            
            # Ajustement pour la longitude, tenant compte de la diminution de la distance couverte par un degré de longitude avec l'augmentation de la latitude
            adjustment_lon = adjustment / math.cos(math.radians(row['GPS__Latitude']))
            
            # Création du carré de 100m autour du point
            geom = box(row['GPS__Longitude'] - adjustment_lon, row['GPS__Latitude'] - adjustment, 
                       row['GPS__Longitude'] + adjustment_lon, row['GPS__Latitude'] + adjustment)
            out_image, out_transform = mask(src, [geom], crop=True, all_touched=True)

            # Conversion et calcul de la moyenne
            out_image = out_image.astype(float)
            out_image[out_image == src.nodata] = np.nan
            mean_val = np.nanmean(out_image)
            nightlights2.append(mean_val)
        
        df['nightlights2'] = nightlights2

    return df
"""

"\nimport rasterio\nfrom rasterio.mask import mask\nfrom shapely.geometry import box\nimport numpy as np\nimport pandas as pd\n\n\nimport math\nimport rasterio\nfrom rasterio.mask import mask\nfrom shapely.geometry import box\nimport numpy as np\nimport pandas as pd\n\ndef calculate_nightlights_100m(df, path_to_tiff):\n    with rasterio.open(path_to_tiff) as src:\n        nightlights2 = []\n        for index, row in df.iterrows():\n            # Calcul de l'ajustement en degrés pour 100 mètres\n            # Rayon moyen de la Terre en mètres\n            earth_radius = 6371000\n            # Distance correspondant à un degré à l'équateur\n            distance_per_degree = (2 * math.pi * earth_radius) / 360\n            # Ajustement pour 100 mètres en degrés\n            adjustment = 100 / distance_per_degree\n            \n            # Ajustement pour la longitude, tenant compte de la diminution de la distance couverte par un degré de longitude avec l'augmentation de la latitude\n    

In [64]:
df_reduit_cleaned.to_csv(os.path.join(BASE_DIR,"DataCIV.csv"), index=False)

In [65]:
df_reduit_cleaned

country  year      hhid  grappe  menage  vague      zae  \
0         CIV  2018     101.0       1       1      1  ABIDJAN   
1         CIV  2018     102.0       1       2      1  ABIDJAN   
2         CIV  2018     103.0       1       3      1  ABIDJAN   
3         CIV  2018     104.0       1       4      1  ABIDJAN   
4         CIV  2018     105.0       1       5      1  ABIDJAN   
...       ...   ...       ...     ...     ...    ...      ...   
12987     CIV  2019  108408.0    1084       8      2   CENTRE   
12988     CIV  2019  108409.0    1084       9      2   CENTRE   
12989     CIV  2019  108410.0    1084      10      2   CENTRE   
12990     CIV  2019  108411.0    1084      11      2   CENTRE   
12991     CIV  2019  108412.0    1084      12      2   CENTRE   

                   region  milieu         milieu2  ...  \
0      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...   
1      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...   
2      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...   
3      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...   
4      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...   
...                   ...     ...             ...  ...   
12987             MORONOU   Rural           Rural  ...   
12988             MORONOU   Rural           Rural  ...   
12989             MORONOU   Rural           Rural  ...   
12990             MORONOU   Rural           Rural  ...   
12991             MORONOU   Rural           Rural  ...   

                          interview__id  GPS__Latitude  GPS__Longitude  \
0      2eb3d29ba9814aa9bf99d6908559e7d2       5.340541       -4.026030   
1      99990d719d6243a38fad96a4d7477742       5.340402       -4.025834   
2      6cf633ef989c4a6a93ec483de1fd8193       5.340151       -4.025953   
3      67feab4e35d141679ec4b867a59cba19       5.340500       -4.026202   
4      dc1f1fa87d8e433e8891a4e55a8baca0       5.339820       -4.025066   
...                                 ...            ...             ...   
12987  103cff29baaf4405863e1043897aa6dc       6.546733       -4.508211   
12988  e3a3deb8965e45c18018d1e5d103d914       6.549112       -4.505840   
12989  45397589c6d44a478051e4089a884c97       6.551556       -4.507530   
12990  505343592b0f4b8b8ede9980f714b8ab       6.552345       -4.507551   
12991  d3431cc126bd44b38fa4976fc3adb753       6.550105       -4.508566   

       GPS__Accuracy GPS__Altitude       GPS__Timestamp nom_prenom_cm  \
0               46.0          39.0  2018-10-29T17:56:23                 
1               47.0          28.0  2018-10-29T17:54:35                 
2               35.0          68.0  2018-10-29T17:51:50                 
3               32.0          59.0  2018-10-29T19:48:39                 
4               49.0          72.0  2018-10-29T18:45:09                 
...              ...           ...                  ...           ...   
12987            7.0         134.0  2019-06-16T19:42:05                 
12988           36.0         131.0  2019-06-17T08:10:57                 
12989           29.0         118.0  2019-06-16T09:30:14                 
12990           19.0         157.0  2019-06-16T10:18:13                 
12991            6.0         134.0  2019-06-16T08:39:10                 

      localisation_menage nightlight_0 nightlights  
0                                  182       175.0  
1                                  182       175.0  
2                                  182       175.0  
3                                  182       175.0  
4                                  182       175.0  
...                   ...          ...         ...  
12987                              175       185.0  
12988                              175       185.0  
12989                              175       185.0  
12990                              176       185.0  
12991                              175       185.0  

[12980 rows x 50 columns]

In [66]:
df_reduit_cleaned['nightlights'].mean()

183.64720724191062

In [67]:
import matplotlib
matplotlib.use('TkAgg')  # Switch to a GUI backend
import matplotlib.pyplot as plt

# Your plotting code here
plt.hist(df_reduit_cleaned['nightlights'], bins=50, color='blue', edgecolor='black')
plt.title('Histogram of Nightlights')
plt.xlabel('Nightlight Intensity')
plt.ylabel('Frequency')
plt.show()


In [68]:
# Assuming df_reduit_cleaned is your DataFrame and 'nightlights' is the column of interest
summary_stats = df_reduit_cleaned['nightlights'].describe()
print(summary_stats)

count    12980.000000
mean       183.647207
std          3.653380
min        171.000000
25%        183.000000
50%        185.000000
75%        186.000000
max        190.000000
Name: nightlights, dtype: float64


In [69]:
# Compter le nombre de valeurs NaN dans 'nightlights'
nan_count = df_reduit_cleaned['nightlights'].isna().sum()
print(f"Nombre de valeurs NaN dans 'nightlights': {nan_count}") 

import matplotlib
matplotlib.use('TkAgg')  # Switch to a GUI backend
import matplotlib.pyplot as plt

# Your plotting code here
plt.hist(df_reduit_cleaned['nightlights'], bins=50, color='blue', edgecolor='black')
plt.title('Histogramme de Nightlights')
plt.xlabel('Intensité Lumineuse nocturnes')
plt.ylabel('Fréquence')
plt.show()
plt.savefig('C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/graphs/histogramme_nightlights.png')

import matplotlib
matplotlib.use('TkAgg')  # Utilisation d'un backend GUI
import matplotlib.pyplot as plt

# Histogramme
plt.hist(df_reduit_cleaned['nightlights'], bins=50, color='blue', edgecolor='black')
plt.title('Histogramme de Nightlights')
plt.xlabel('Intensité Lumineuse nocturnes')
plt.ylabel('Fréquence')

# Sauvegarde
plt.savefig('C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/graphs/histogramme_nightlights_deuxième.png')

# Affichage de l'histogramme
plt.show() 

summary_stats = df_reduit_cleaned['nightlights'].describe()
print(summary_stats) 

# Calcul de la corrélation entre 'pcexp' et 'nightlights'
#la corrélation de Pearson entre les colonnes pcexp et nightlights et affiche le résultat.

correlation_pcexp_nightlights = df_reduit_cleaned['pcexp'].corr(df_reduit_cleaned['nightlights'])

print(f"Corrélation entre 'pcexp' et 'nightlights': {correlation_pcexp_nightlights}")

import matplotlib.pyplot as plt

# Créer le scatter plot
plt.figure(figsize=(10, 6))  # Définit la taille de la figure
plt.scatter(df_reduit_cleaned['pcexp'], df_reduit_cleaned['nightlights'], alpha=0.5)  # Crée le scatter plot
plt.title('Scatter plot entre pcexp et nightlights')  # Titre du graphique
plt.xlabel('pcexp')  # Label pour l'axe des x
plt.ylabel('nightlights')  # Label pour l'axe des y

# Sauvegarder le graphique dans le dossier 'graphs'
plt.savefig('C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/graphs/scatter_pcexp_vs_nightlights.png')

# Afficher le graphique
plt.show()



Nombre de valeurs NaN dans 'nightlights': 0
count    12980.000000
mean       183.647207
std          3.653380
min        171.000000
25%        183.000000
50%        185.000000
75%        186.000000
max        190.000000
Name: nightlights, dtype: float64
Corrélation entre 'pcexp' et 'nightlights': -0.18968493652167154


#### Automatisation

In [70]:
import math
import rasterio
from rasterio.mask import mask
from shapely.geometry import box
import numpy as np
import pandas as pd

def create_space_adjusted(lat, lon, s):
    earth_radius = 6378137  # Rayon moyen de la Terre en mètres
    distance_per_degree = (2 * math.pi * earth_radius) / 360  # Distance par degré à l'équateur
    adjustment = s / distance_per_degree  # Ajustement en degrés pour s mètres
    adjustment_lon = adjustment / math.cos(math.radians(lat))  # Ajustement longitude
    return box(lon - adjustment_lon, lat - adjustment, lon + adjustment_lon, lat + adjustment)

def calculate_nightlights_custom(df, path_to_tiff, distance_m):
    column_name = f'nightlights_{distance_m}m'
    with rasterio.open(path_to_tiff) as src:
        nightlights = []
        for index, row in df.iterrows():
            geom = create_space_adjusted(row['GPS__Latitude'], row['GPS__Longitude'], distance_m / 2)
            out_image, out_transform = mask(src, [geom], crop=True, all_touched=True)
            out_image = out_image.astype(float)
            out_image[out_image == src.nodata] = np.nan  # Convertir les no_data en NaN
            mean_val = np.nanmean(out_image)  # Calcul de la moyenne, en excluant les NaN
            nightlights.append(mean_val)
        df[column_name] = nightlights
    return df

def automate_process(df, path_to_tiff, distance_m):
    base_path = 'C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/graphs/'
    
    # Calculer l'intensité lumineuse pour chaque point avec la distance spécifiée
    df = calculate_nightlights_custom(df, path_to_tiff, distance_m)
    
    # Génération d'un histogramme global pour la distance_m spécifiée
    histogram_path = f'{base_path}histogramme_nightlights_{distance_m}m.png'
    plt.hist(df[f'nightlights_{distance_m}m'].dropna(), bins=20, edgecolor='black')
    plt.title(f'Histogramme des Lumières Nocturnes {distance_m}m')
    plt.xlabel('Intensité Lumineuse Nocturne')
    plt.ylabel('Fréquence')
    plt.savefig(histogram_path)
    plt.close()
    
    # Afficher des statistiques résumées et le nombre de valeurs NaN pour la nouvelle colonne
    nan_count = df[f'nightlights_{distance_m}m'].isna().sum()
    print(f"Nombre de valeurs NaN dans 'nightlights_{distance_m}m': {nan_count}")
    
    summary_stats = df[f'nightlights_{distance_m}m'].describe()
    print(summary_stats)

### Les intensités lumineuses nocturnes considérant un rayon de 50 mètres


In [71]:
path_to_tiff='C:\\Users\\d\\Desktop\\Programme du projet sur CNN pauvreté\\Data\\NIGHTLIGHTS\\VNL_v2_npp_2018_global_vcmslcfg_c202101211500.cvg.tif'
distance_m = 50  # Définir la distance en mètres
automate_process(df_reduit_cleaned, path_to_tiff, distance_m)

C:\Users\d\AppData\Local\Temp\ipykernel_24360\3175703501.py:26: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = nightlights


Nombre de valeurs NaN dans 'nightlights_50m': 0
count    12980.000000
mean       183.647689
std          3.653234
min        171.000000
25%        183.000000
50%        185.000000
75%        186.000000
max        190.000000
Name: nightlights_50m, dtype: float64


In [74]:
# Calcul de la corrélation entre 'pcexp' et 'nightlighst_50m'
#la corrélation de Pearson entre les colonnes pcexp et nightlights_50m et affiche le résultat.
correlation_pcexp_nightlights_50m = df_reduit_cleaned['pcexp'].corr(df_reduit_cleaned['nightlights_50m'])
print(f"Corrélation entre 'pcexp' et 'nightlight_50m': {correlation_pcexp_nightlights_50m}")

Corrélation entre 'pcexp' et 'nightlight_50m': -0.18955508034721524


In [72]:
df_reduit_cleaned

country  year      hhid  grappe  menage  vague      zae  \
0         CIV  2018     101.0       1       1      1  ABIDJAN   
1         CIV  2018     102.0       1       2      1  ABIDJAN   
2         CIV  2018     103.0       1       3      1  ABIDJAN   
3         CIV  2018     104.0       1       4      1  ABIDJAN   
4         CIV  2018     105.0       1       5      1  ABIDJAN   
...       ...   ...       ...     ...     ...    ...      ...   
12987     CIV  2019  108408.0    1084       8      2   CENTRE   
12988     CIV  2019  108409.0    1084       9      2   CENTRE   
12989     CIV  2019  108410.0    1084      10      2   CENTRE   
12990     CIV  2019  108411.0    1084      11      2   CENTRE   
12991     CIV  2019  108412.0    1084      12      2   CENTRE   

                   region  milieu         milieu2  ...  GPS__Latitude  \
0      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...       5.340541   
1      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...       5.340402   
2      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...       5.340151   
3      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...       5.340500   
4      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...       5.339820   
...                   ...     ...             ...  ...            ...   
12987             MORONOU   Rural           Rural  ...       6.546733   
12988             MORONOU   Rural           Rural  ...       6.549112   
12989             MORONOU   Rural           Rural  ...       6.551556   
12990             MORONOU   Rural           Rural  ...       6.552345   
12991             MORONOU   Rural           Rural  ...       6.550105   

       GPS__Longitude  GPS__Accuracy  GPS__Altitude       GPS__Timestamp  \
0           -4.026030           46.0           39.0  2018-10-29T17:56:23   
1           -4.025834           47.0           28.0  2018-10-29T17:54:35   
2           -4.025953           35.0           68.0  2018-10-29T17:51:50   
3           -4.026202           32.0           59.0  2018-10-29T19:48:39   
4           -4.025066           49.0           72.0  2018-10-29T18:45:09   
...               ...            ...            ...                  ...   
12987       -4.508211            7.0          134.0  2019-06-16T19:42:05   
12988       -4.505840           36.0          131.0  2019-06-17T08:10:57   
12989       -4.507530           29.0          118.0  2019-06-16T09:30:14   
12990       -4.507551           19.0          157.0  2019-06-16T10:18:13   
12991       -4.508566            6.0          134.0  2019-06-16T08:39:10   

       nom_prenom_cm localisation_menage nightlight_0 nightlights  \
0                                                 182       175.0   
1                                                 182       175.0   
2                                                 182       175.0   
3                                                 182       175.0   
4                                                 182       175.0   
...              ...                 ...          ...         ...   
12987                                             175       185.0   
12988                                             175       185.0   
12989                                             175       185.0   
12990                                             176       185.0   
12991                                             175       185.0   

      nightlights_50m  
0               175.0  
1               175.0  
2               175.0  
3               175.0  
4               175.0  
...               ...  
12987           185.0  
12988           185.0  
12989           185.0  
12990           185.0  
12991           185.0  

[12980 rows x 51 columns]

### Les intensités lumineuses nocturnes considérant un rayon de 20 mètres


In [75]:
path_to_tiff='C:\\Users\\d\\Desktop\\Programme du projet sur CNN pauvreté\\Data\\NIGHTLIGHTS\\VNL_v2_npp_2018_global_vcmslcfg_c202101211500.cvg.tif'
distance_m = 20  # Définir la distance en mètres
automate_process(df_reduit_cleaned, path_to_tiff, distance_m)

C:\Users\d\AppData\Local\Temp\ipykernel_24360\3175703501.py:26: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = nightlights


Nombre de valeurs NaN dans 'nightlights_20m': 0
count    12980.000000
mean       183.647592
std          3.653324
min        171.000000
25%        183.000000
50%        185.000000
75%        186.000000
max        190.000000
Name: nightlights_20m, dtype: float64


In [77]:
df_reduit_cleaned

country  year      hhid  grappe  menage  vague      zae  \
0         CIV  2018     101.0       1       1      1  ABIDJAN   
1         CIV  2018     102.0       1       2      1  ABIDJAN   
2         CIV  2018     103.0       1       3      1  ABIDJAN   
3         CIV  2018     104.0       1       4      1  ABIDJAN   
4         CIV  2018     105.0       1       5      1  ABIDJAN   
...       ...   ...       ...     ...     ...    ...      ...   
12987     CIV  2019  108408.0    1084       8      2   CENTRE   
12988     CIV  2019  108409.0    1084       9      2   CENTRE   
12989     CIV  2019  108410.0    1084      10      2   CENTRE   
12990     CIV  2019  108411.0    1084      11      2   CENTRE   
12991     CIV  2019  108412.0    1084      12      2   CENTRE   

                   region  milieu         milieu2  ...  GPS__Longitude  \
0      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...       -4.026030   
1      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...       -4.025834   
2      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...       -4.025953   
3      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...       -4.026202   
4      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...       -4.025066   
...                   ...     ...             ...  ...             ...   
12987             MORONOU   Rural           Rural  ...       -4.508211   
12988             MORONOU   Rural           Rural  ...       -4.505840   
12989             MORONOU   Rural           Rural  ...       -4.507530   
12990             MORONOU   Rural           Rural  ...       -4.507551   
12991             MORONOU   Rural           Rural  ...       -4.508566   

       GPS__Accuracy  GPS__Altitude       GPS__Timestamp nom_prenom_cm  \
0               46.0           39.0  2018-10-29T17:56:23                 
1               47.0           28.0  2018-10-29T17:54:35                 
2               35.0           68.0  2018-10-29T17:51:50                 
3               32.0           59.0  2018-10-29T19:48:39                 
4               49.0           72.0  2018-10-29T18:45:09                 
...              ...            ...                  ...           ...   
12987            7.0          134.0  2019-06-16T19:42:05                 
12988           36.0          131.0  2019-06-17T08:10:57                 
12989           29.0          118.0  2019-06-16T09:30:14                 
12990           19.0          157.0  2019-06-16T10:18:13                 
12991            6.0          134.0  2019-06-16T08:39:10                 

       localisation_menage nightlight_0 nightlights nightlights_50m  \
0                                   182       175.0           175.0   
1                                   182       175.0           175.0   
2                                   182       175.0           175.0   
3                                   182       175.0           175.0   
4                                   182       175.0           175.0   
...                    ...          ...         ...             ...   
12987                               175       185.0           185.0   
12988                               175       185.0           185.0   
12989                               175       185.0           185.0   
12990                               176       185.0           185.0   
12991                               175       185.0           185.0   

      nightlights_20m  
0               175.0  
1               175.0  
2               175.0  
3               175.0  
4               175.0  
...               ...  
12987           185.0  
12988           185.0  
12989           185.0  
12990           185.0  
12991           185.0  

[12980 rows x 52 columns]

### Les intensités lumineuses nocturnes considérant un rayon de 25 mètres

In [78]:
path_to_tiff='C:\\Users\\d\\Desktop\\Programme du projet sur CNN pauvreté\\Data\\NIGHTLIGHTS\\VNL_v2_npp_2018_global_vcmslcfg_c202101211500.cvg.tif'
distance_m = 25  # Définir la distance en mètres
automate_process(df_reduit_cleaned, path_to_tiff, distance_m)

C:\Users\d\AppData\Local\Temp\ipykernel_24360\3175703501.py:26: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = nightlights


Nombre de valeurs NaN dans 'nightlights_25m': 0
count    12980.000000
mean       183.647592
std          3.653303
min        171.000000
25%        183.000000
50%        185.000000
75%        186.000000
max        190.000000
Name: nightlights_25m, dtype: float64


In [81]:
df_reduit_cleaned

country  year      hhid  grappe  menage  vague      zae  \
0         CIV  2018     101.0       1       1      1  ABIDJAN   
1         CIV  2018     102.0       1       2      1  ABIDJAN   
2         CIV  2018     103.0       1       3      1  ABIDJAN   
3         CIV  2018     104.0       1       4      1  ABIDJAN   
4         CIV  2018     105.0       1       5      1  ABIDJAN   
...       ...   ...       ...     ...     ...    ...      ...   
12987     CIV  2019  108408.0    1084       8      2   CENTRE   
12988     CIV  2019  108409.0    1084       9      2   CENTRE   
12989     CIV  2019  108410.0    1084      10      2   CENTRE   
12990     CIV  2019  108411.0    1084      11      2   CENTRE   
12991     CIV  2019  108412.0    1084      12      2   CENTRE   

                   region  milieu         milieu2  ...  GPS__Altitude  \
0      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...           39.0   
1      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...           28.0   
2      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...           68.0   
3      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...           59.0   
4      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...           72.0   
...                   ...     ...             ...  ...            ...   
12987             MORONOU   Rural           Rural  ...          134.0   
12988             MORONOU   Rural           Rural  ...          131.0   
12989             MORONOU   Rural           Rural  ...          118.0   
12990             MORONOU   Rural           Rural  ...          157.0   
12991             MORONOU   Rural           Rural  ...          134.0   

            GPS__Timestamp  nom_prenom_cm  localisation_menage nightlight_0  \
0      2018-10-29T17:56:23                                              182   
1      2018-10-29T17:54:35                                              182   
2      2018-10-29T17:51:50                                              182   
3      2018-10-29T19:48:39                                              182   
4      2018-10-29T18:45:09                                              182   
...                    ...            ...                  ...          ...   
12987  2019-06-16T19:42:05                                              175   
12988  2019-06-17T08:10:57                                              175   
12989  2019-06-16T09:30:14                                              175   
12990  2019-06-16T10:18:13                                              176   
12991  2019-06-16T08:39:10                                              175   

       nightlights nightlights_50m nightlights_20m nightlights_25m  \
0            175.0           175.0           175.0           175.0   
1            175.0           175.0           175.0           175.0   
2            175.0           175.0           175.0           175.0   
3            175.0           175.0           175.0           175.0   
4            175.0           175.0           175.0           175.0   
...            ...             ...             ...             ...   
12987        185.0           185.0           185.0           185.0   
12988        185.0           185.0           185.0           185.0   
12989        185.0           185.0           185.0           185.0   
12990        185.0           185.0           185.0           185.0   
12991        185.0           185.0           185.0           185.0   

      nightlights_30m  
0               175.0  
1               175.0  
2               175.0  
3               175.0  
4               175.0  
...               ...  
12987           185.0  
12988           185.0  
12989           185.0  
12990           185.0  
12991           185.0  

[12980 rows x 54 columns]

### Les intensités lumineuses nocturnes considérant un rayon de 30 mètres

In [79]:
path_to_tiff='C:\\Users\\d\\Desktop\\Programme du projet sur CNN pauvreté\\Data\\NIGHTLIGHTS\\VNL_v2_npp_2018_global_vcmslcfg_c202101211500.cvg.tif'
distance_m = 30  # Définir la distance en mètres
automate_process(df_reduit_cleaned, path_to_tiff, distance_m)

C:\Users\d\AppData\Local\Temp\ipykernel_24360\3175703501.py:26: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = nightlights


Nombre de valeurs NaN dans 'nightlights_30m': 0
count    12980.000000
mean       183.647438
std          3.653471
min        171.000000
25%        183.000000
50%        185.000000
75%        186.000000
max        190.000000
Name: nightlights_30m, dtype: float64


### Les intensités lumineuses nocturnes considérant un rayon de 150 mètres

In [82]:
path_to_tiff='C:\\Users\\d\\Desktop\\Programme du projet sur CNN pauvreté\\Data\\NIGHTLIGHTS\\VNL_v2_npp_2018_global_vcmslcfg_c202101211500.cvg.tif'
distance_m = 150  # Définir la distance en mètres
automate_process(df_reduit_cleaned, path_to_tiff, distance_m)

C:\Users\d\AppData\Local\Temp\ipykernel_24360\3175703501.py:26: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = nightlights


Nombre de valeurs NaN dans 'nightlights_150m': 0
count    12980.000000
mean       183.647015
std          3.652612
min        171.000000
25%        183.000000
50%        185.000000
75%        186.000000
max        190.000000
Name: nightlights_150m, dtype: float64


### Les intensités lumineuses nocturnes considérant un rayon de 1000 mètres

In [83]:
path_to_tiff='C:\\Users\\d\\Desktop\\Programme du projet sur CNN pauvreté\\Data\\NIGHTLIGHTS\\VNL_v2_npp_2018_global_vcmslcfg_c202101211500.cvg.tif'
distance_m = 1000  # Définir la distance en mètres
automate_process(df_reduit_cleaned, path_to_tiff, distance_m)

C:\Users\d\AppData\Local\Temp\ipykernel_24360\3175703501.py:26: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = nightlights


Nombre de valeurs NaN dans 'nightlights_1000m': 0
count    12980.000000
mean       183.638089
std          3.667681
min        159.500000
25%        183.000000
50%        185.000000
75%        186.000000
max        189.777778
Name: nightlights_1000m, dtype: float64


### Les intensités lumineuses nocturnes considérant un rayon de 5000 mètres

In [84]:
path_to_tiff='C:\\Users\\d\\Desktop\\Programme du projet sur CNN pauvreté\\Data\\NIGHTLIGHTS\\VNL_v2_npp_2018_global_vcmslcfg_c202101211500.cvg.tif'
distance_m = 5000  # Définir la distance en mètres
automate_process(df_reduit_cleaned, path_to_tiff, distance_m)

C:\Users\d\AppData\Local\Temp\ipykernel_24360\3175703501.py:26: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = nightlights


Nombre de valeurs NaN dans 'nightlights_5000m': 0
count    12980.000000
mean       183.668538
std          3.570050
min        163.174242
25%        183.007576
50%        185.000000
75%        186.000000
max        189.645833
Name: nightlights_5000m, dtype: float64


In [85]:
df_reduit_cleaned

country  year      hhid  grappe  menage  vague      zae  \
0         CIV  2018     101.0       1       1      1  ABIDJAN   
1         CIV  2018     102.0       1       2      1  ABIDJAN   
2         CIV  2018     103.0       1       3      1  ABIDJAN   
3         CIV  2018     104.0       1       4      1  ABIDJAN   
4         CIV  2018     105.0       1       5      1  ABIDJAN   
...       ...   ...       ...     ...     ...    ...      ...   
12987     CIV  2019  108408.0    1084       8      2   CENTRE   
12988     CIV  2019  108409.0    1084       9      2   CENTRE   
12989     CIV  2019  108410.0    1084      10      2   CENTRE   
12990     CIV  2019  108411.0    1084      11      2   CENTRE   
12991     CIV  2019  108412.0    1084      12      2   CENTRE   

                   region  milieu         milieu2  ...  localisation_menage  \
0      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...                        
1      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...                        
2      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...                        
3      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...                        
4      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...                        
...                   ...     ...             ...  ...                  ...   
12987             MORONOU   Rural           Rural  ...                        
12988             MORONOU   Rural           Rural  ...                        
12989             MORONOU   Rural           Rural  ...                        
12990             MORONOU   Rural           Rural  ...                        
12991             MORONOU   Rural           Rural  ...                        

       nightlight_0  nightlights  nightlights_50m nightlights_20m  \
0               182        175.0            175.0           175.0   
1               182        175.0            175.0           175.0   
2               182        175.0            175.0           175.0   
3               182        175.0            175.0           175.0   
4               182        175.0            175.0           175.0   
...             ...          ...              ...             ...   
12987           175        185.0            185.0           185.0   
12988           175        185.0            185.0           185.0   
12989           175        185.0            185.0           185.0   
12990           176        185.0            185.0           185.0   
12991           175        185.0            185.0           185.0   

       nightlights_25m nightlights_30m nightlights_150m nightlights_1000m  \
0                175.0           175.0            175.0             175.0   
1                175.0           175.0            175.0             175.0   
2                175.0           175.0            175.0             175.0   
3                175.0           175.0            175.0             175.0   
4                175.0           175.0            175.0             175.0   
...                ...             ...              ...               ...   
12987            185.0           185.0            185.0             185.0   
12988            185.0           185.0            185.0             185.0   
12989            185.0           185.0            185.0             185.0   
12990            185.0           185.0            185.0             185.0   
12991            185.0           185.0            185.0             185.0   

      nightlights_5000m  
0            174.888889  
1            174.888889  
2            174.888889  
3            174.888889  
4            174.765152  
...                 ...  
12987        185.000000  
12988        185.000000  
12989        185.000000  
12990        185.000000  
12991        185.000000  

[12980 rows x 57 columns]

In [86]:
import pandas as pd


# Sélection des colonnes d'intérêt pour la corrélation
columns_of_interest = [
    "pcexp",
    "nightlight_0",
    "nightlights",
    "nightlights_50m",
    "nightlights_20m",
    "nightlights_25m",
    "nightlights_30m",
    "nightlights_150m",
    "nightlights_1000m",
    "nightlights_5000m"
]

# Filtrage le DataFrame pour ne garder que les colonnes d'intérêt
df_filtered = df_reduit_cleaned[columns_of_interest]

# Calculer le tableau de corrélation
correlation_matrix = df_filtered.corr()

# Afficher le tableau de corrélation
#print(correlation_matrix)

# Si vous voulez spécifiquement voir la corrélation de "pcexp" avec les autres variables
print(correlation_matrix['pcexp'])


pcexp                1.000000
nightlight_0         0.016664
nightlights         -0.189685
nightlights_50m     -0.189555
nightlights_20m     -0.189526
nightlights_25m     -0.189534
nightlights_30m     -0.189521
nightlights_150m    -0.189878
nightlights_1000m   -0.187754
nightlights_5000m   -0.192260
Name: pcexp, dtype: float64


In [87]:
import seaborn as sns
import matplotlib.pyplot as plt

# Calcul et préparation de la matrice de corrélation
columns_of_interest = [
    "pcexp",
    "nightlight_0",
    "nightlights",
    "nightlights_50m",
    "nightlights_20m",
    "nightlights_25m",
    "nightlights_30m",
    "nightlights_150m",
    "nightlights_1000m",
    "nightlights_5000m"
]

df_filtered = df_reduit_cleaned[columns_of_interest]
correlation_matrix = df_filtered.corr()

# Création de la heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm", fmt=".2f", linewidths=.5, cbar_kws={'label': 'Coefficient de Corrélation'})
plt.title('Matrice de Corrélation des Variables de Lumières Nocturnes et pcexp')
plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)
plt.tight_layout()

# Sauvegarder la heatmap dans un fichier
save_path = 'C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/graphs/heatmap_correlation.png'
plt.savefig(save_path)

# Fermer la figure pour libérer la mémoire
#plt.close()
# Affichage du heatmap
plt.show()

In [88]:
df_reduit_cleaned

country  year      hhid  grappe  menage  vague      zae  \
0         CIV  2018     101.0       1       1      1  ABIDJAN   
1         CIV  2018     102.0       1       2      1  ABIDJAN   
2         CIV  2018     103.0       1       3      1  ABIDJAN   
3         CIV  2018     104.0       1       4      1  ABIDJAN   
4         CIV  2018     105.0       1       5      1  ABIDJAN   
...       ...   ...       ...     ...     ...    ...      ...   
12987     CIV  2019  108408.0    1084       8      2   CENTRE   
12988     CIV  2019  108409.0    1084       9      2   CENTRE   
12989     CIV  2019  108410.0    1084      10      2   CENTRE   
12990     CIV  2019  108411.0    1084      11      2   CENTRE   
12991     CIV  2019  108412.0    1084      12      2   CENTRE   

                   region  milieu         milieu2  ...  localisation_menage  \
0      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...                        
1      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...                        
2      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...                        
3      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...                        
4      AUTONOME D'ABIDJAN  Urbain  Abidjan urbain  ...                        
...                   ...     ...             ...  ...                  ...   
12987             MORONOU   Rural           Rural  ...                        
12988             MORONOU   Rural           Rural  ...                        
12989             MORONOU   Rural           Rural  ...                        
12990             MORONOU   Rural           Rural  ...                        
12991             MORONOU   Rural           Rural  ...                        

       nightlight_0  nightlights  nightlights_50m nightlights_20m  \
0               182        175.0            175.0           175.0   
1               182        175.0            175.0           175.0   
2               182        175.0            175.0           175.0   
3               182        175.0            175.0           175.0   
4               182        175.0            175.0           175.0   
...             ...          ...              ...             ...   
12987           175        185.0            185.0           185.0   
12988           175        185.0            185.0           185.0   
12989           175        185.0            185.0           185.0   
12990           176        185.0            185.0           185.0   
12991           175        185.0            185.0           185.0   

       nightlights_25m nightlights_30m nightlights_150m nightlights_1000m  \
0                175.0           175.0            175.0             175.0   
1                175.0           175.0            175.0             175.0   
2                175.0           175.0            175.0             175.0   
3                175.0           175.0            175.0             175.0   
4                175.0           175.0            175.0             175.0   
...                ...             ...              ...               ...   
12987            185.0           185.0            185.0             185.0   
12988            185.0           185.0            185.0             185.0   
12989            185.0           185.0            185.0             185.0   
12990            185.0           185.0            185.0             185.0   
12991            185.0           185.0            185.0             185.0   

      nightlights_5000m  
0            174.888889  
1            174.888889  
2            174.888889  
3            174.888889  
4            174.765152  
...                 ...  
12987        185.000000  
12988        185.000000  
12989        185.000000  
12990        185.000000  
12991        185.000000  

[12980 rows x 57 columns]

In [89]:
df_reduit_cleaned.to_csv(os.path.join(BASE_DIR,"DataCIV2.csv"), index=False)

### Partition des intensités lumineuses nocturnes en catégories

In [91]:
# Étape 1 : Importation des bibliothèques nécessaires
import pandas as pd
from sklearn.mixture import GaussianMixture
import numpy as np
import matplotlib.pyplot as plt

# Étape 2 : Chargement des données
file_path = 'C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/DataCIV2.csv'  # Chemin du fichier à ajuster selon le besoin
data = pd.read_csv(file_path)

# Étape 3 : Sélection de la colonne 'nightlights'
X = data['nightlights'].values.reshape(-1, 1)  # Redimensionnement nécessaire pour le GMM

# Étape 4 : Application du GMM pour trouver le nombre optimal de clusters
n_components_range = range(1, 11)  # Test de 1 à 10 clusters
bics = []
for n_components in n_components_range:
    gmm = GaussianMixture(n_components=n_components, random_state=42)
    gmm.fit(X)
    bics.append(gmm.bic(X))
# Trouver le nombre optimal de composants en fonction du score BIC le plus bas
optimal_n_components = n_components_range[np.argmin(bics)]

# Étape 5 : Ajustement du modèle GMM avec le nombre optimal de composantes
gmm_optimal = GaussianMixture(n_components=optimal_n_components, random_state=42)
gmm_optimal.fit(X)

# Étape 6 : Assignation de chaque point de données à son cluster
clusters = gmm_optimal.predict(X)

# Étape 7 : Ajout des assignations de cluster au dataframe
data['cluster'] = clusters

# Affichage des premières lignes pour vérifier les résultats
print(data.head())
print(gmm)
print(gmm_optimal.fit(X))
print(gmm_optimal)
print(clusters)

  country  year   hhid  grappe  menage  vague      zae              region  \
0     CIV  2018  101.0       1       1      1  ABIDJAN  AUTONOME D'ABIDJAN   
1     CIV  2018  102.0       1       2      1  ABIDJAN  AUTONOME D'ABIDJAN   
2     CIV  2018  103.0       1       3      1  ABIDJAN  AUTONOME D'ABIDJAN   
3     CIV  2018  104.0       1       4      1  ABIDJAN  AUTONOME D'ABIDJAN   
4     CIV  2018  105.0       1       5      1  ABIDJAN  AUTONOME D'ABIDJAN   

   milieu         milieu2  ...  nightlight_0  nightlights  nightlights_50m  \
0  Urbain  Abidjan urbain  ...           182        175.0            175.0   
1  Urbain  Abidjan urbain  ...           182        175.0            175.0   
2  Urbain  Abidjan urbain  ...           182        175.0            175.0   
3  Urbain  Abidjan urbain  ...           182        175.0            175.0   
4  Urbain  Abidjan urbain  ...           182        175.0            175.0   

   nightlights_20m nightlights_25m  nightlights_30m nightlight

In [93]:
# Examination du modèle GMM

# Nombre de clusters
print(f"Nombre optimal de clusters (composants) : {optimal_n_components}")

# Probabilités d'appartenance aux clusters pour quelques points
probabilities = gmm_optimal.predict_proba(X)
print("Probabilités d'appartenance aux clusters pour les 5 premiers points :")
print(probabilities[:5])

# Moyennes des composants
print("Moyennes des clusters :")
print(gmm_optimal.means_)

# Covariances des composants
print("Covariances des clusters :")
print(gmm_optimal.covariances_)

# Poids des composants (la probabilité a priori de chaque composant)
print("Poids des clusters :")
print(gmm_optimal.weights_)

# Visualisation des moyennes des clusters
plt.figure(figsize=(10, 6))
plt.title("Moyennes des clusters")
plt.scatter(range(optimal_n_components), gmm_optimal.means_.reshape(-1), color='red')
plt.xlabel("Cluster")
plt.ylabel("Moyenne de nightlights")
plt.xticks(range(optimal_n_components))
plt.grid(True)
plt.show()


Nombre optimal de clusters (composants) : 9
Probabilités d'appartenance aux clusters pour les 5 premiers points :
[[0.         0.94626965 0.         0.         0.01829319 0.02180491
  0.         0.         0.01363226]
 [0.         0.94626965 0.         0.         0.01829319 0.02180491
  0.         0.         0.01363226]
 [0.         0.94626965 0.         0.         0.01829319 0.02180491
  0.         0.         0.01363226]
 [0.         0.94626965 0.         0.         0.01829319 0.02180491
  0.         0.         0.01363226]
 [0.         0.94626965 0.         0.         0.01829319 0.02180491
  0.         0.         0.01363226]]
Moyennes des clusters :
[[187.        ]
 [174.84297604]
 [183.        ]
 [185.        ]
 [177.21744647]
 [181.0022024 ]
 [186.        ]
 [184.        ]
 [173.11781088]]
Covariances des clusters :
[[[1.00000000e-06]]

 [[2.62707798e-01]]

 [[1.00000000e-06]]

 [[1.00000000e-06]]

 [[7.59389668e-01]]

 [[6.88527210e+00]]

 [[1.00000000e-06]]

 [[1.00000000e-06]]

 

In [92]:
# Importation des bibliothèques nécessaires pour la visualisation
import matplotlib.pyplot as plt
import seaborn as sns

# Paramètres pour améliorer l'esthétique des graphiques
sns.set(style="whitegrid")

# Création d'un histogramme avec les clusters
plt.figure(figsize=(12, 6))  # Définit la taille de la figure

# Boucle sur chaque cluster pour le plotter
for cluster_id in data['cluster'].unique():
    # Sélection des données appartenant au cluster courant
    cluster_data = data[data['cluster'] == cluster_id]['nightlights']
    sns.histplot(cluster_data, label=f'Cluster {cluster_id}', kde=False, bins=20, stat="density")

plt.title('Distribution des valeurs de "nightlights" par cluster')
plt.xlabel('Valeurs de nightlights')
plt.ylabel('Densité')
plt.legend()  # Ajoute une légende pour identifier chaque cluster

plt.show()

In [97]:
# Importation des bibliothèques nécessaires
import pandas as pd
from sklearn.mixture import GaussianMixture
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid")

# Chargement des données
file_path = 'C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/DataCIV2.csv' 
data = pd.read_csv(file_path)

# Liste des colonnes pour l'application du GMM
columns_to_cluster = [
    "nightlights", "nightlight_0", "nightlights_50m", "nightlights_20m",
    "nightlights_25m", "nightlights_30m", "nightlights_150m", 
    "nightlights_1000m", "nightlights_5000m"
]

# Application du GMM et visualisation pour chaque colonne spécifiée
for col in columns_to_cluster:
    X = data[col].values.reshape(-1, 1)  # Redimensionnement nécessaire pour le GMM
    
    # Application du GMM pour trouver le nombre optimal de clusters
    n_components_range = range(1, 11)
    bics = []
    for n_components in n_components_range:
        gmm = GaussianMixture(n_components=n_components, random_state=42)
        gmm.fit(X)
        bics.append(gmm.bic(X))
    optimal_n_components = n_components_range[np.argmin(bics)]

    # Ajustement du modèle GMM avec le nombre optimal de composantes
    gmm_optimal = GaussianMixture(n_components=optimal_n_components, random_state=42)
    gmm_optimal.fit(X)
    
    # Assignation de chaque point de données à son cluster
    clusters = gmm_optimal.predict(X)
    
    # Ajout des assignations de cluster au dataframe
    data[f'cluster_{col}'] = clusters
    
    # Visualisation des moyennes des clusters
    plt.figure(figsize=(10, 6))
    plt.title(f"Moyennes des clusters pour {col}")
    plt.scatter(range(optimal_n_components), gmm_optimal.means_.reshape(-1), color='red')
    plt.xlabel("Cluster")
    plt.ylabel(f"Moyenne de {col}")
    plt.xticks(range(optimal_n_components))
    plt.grid(True)
    plt.savefig(f"C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/graphs/cluster_means_{col}.png")  # Sauvegarde du graphique
    plt.close()
    
    # Création et sauvegarde d'un histogramme des clusters
    plt.figure(figsize=(12, 6))
    for cluster_id in np.unique(clusters):
        sns.histplot(data[data[f'cluster_{col}'] == cluster_id][col], label=f'Cluster {cluster_id}', kde=False, bins=20, stat="density")
    plt.title(f'Distribution des valeurs de "{col}" par cluster')
    plt.xlabel(f'Valeurs de {col}')
    plt.ylabel('Densité')
    plt.legend()
    plt.savefig(f"C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/graphs/histogram_clusters_{col}.png")  # Sauvegarde de l'histogramme
    plt.close()


In [95]:
import pandas as pd
from sklearn.mixture import GaussianMixture
import numpy as np

# Chargement des données
file_path = 'C:/Users/d/Desktop/Programme du projet sur CNN pauvreté2/DataCIV2.csv'  # Ajustez selon votre besoin
data = pd.read_csv(file_path)

# Liste des colonnes pour l'application du GMM
columns_to_cluster = [
    "nightlights", "nightlight_0", "nightlights_50m", "nightlights_20m",
    "nightlights_25m", "nightlights_30m", "nightlights_150m", 
    "nightlights_1000m", "nightlights_5000m"
]

for col in columns_to_cluster:
    print(f"\nTraitement de la colonne : {col}")
    X = data[col].values.reshape(-1, 1)  # Redimensionnement pour le GMM
    
    # Application du GMM pour trouver le nombre optimal de clusters
    n_components_range = range(1, 11)
    bics = []
    for n_components in n_components_range:
        gmm = GaussianMixture(n_components=n_components, random_state=42)
        gmm.fit(X)
        bics.append(gmm.bic(X))
    optimal_n_components = n_components_range[np.argmin(bics)]
    gmm_optimal = GaussianMixture(n_components=optimal_n_components, random_state=42)
    gmm_optimal.fit(X)

    # Affichage des informations du modèle GMM
    print(f"Nombre optimal de clusters (composants) : {optimal_n_components}")
    
    probabilities = gmm_optimal.predict_proba(X)
    print("Probabilités d'appartenance aux clusters pour les 5 premiers points :")
    print(probabilities[:5])
    
    print("Moyennes des clusters :")
    print(gmm_optimal.means_)
    
    print("Covariances des clusters :")
    print(gmm_optimal.covariances_)
    
    print("Poids des clusters :")
    print(gmm_optimal.weights_)



Traitement de la colonne : nightlights
Nombre optimal de clusters (composants) : 9
Probabilités d'appartenance aux clusters pour les 5 premiers points :
[[0.         0.94626965 0.         0.         0.01829319 0.02180491
  0.         0.         0.01363226]
 [0.         0.94626965 0.         0.         0.01829319 0.02180491
  0.         0.         0.01363226]
 [0.         0.94626965 0.         0.         0.01829319 0.02180491
  0.         0.         0.01363226]
 [0.         0.94626965 0.         0.         0.01829319 0.02180491
  0.         0.         0.01363226]
 [0.         0.94626965 0.         0.         0.01829319 0.02180491
  0.         0.         0.01363226]]
Moyennes des clusters :
[[187.        ]
 [174.84297604]
 [183.        ]
 [185.        ]
 [177.21744647]
 [181.0022024 ]
 [186.        ]
 [184.        ]
 [173.11781088]]
Covariances des clusters :
[[[1.00000000e-06]]

 [[2.62707798e-01]]

 [[1.00000000e-06]]

 [[1.00000000e-06]]

 [[7.59389668e-01]]

 [[6.88527210e+00]]

 [[

En utilisant le Mixture Gaussian Model pour trouver le nombre de classe optimal, on se rend compte que pour la plupart des rayons d'éloignement des ménages, on a environ 10 classes que l'on peut former, à l'exception du rayon de 100 mètre qui en a 9.